var found = true;
var grade = 88.5;
var firstName = "Robert";
var lastName = 'Dumitru';
var anyType = "A variable defined with 'any' can have any type assigned";
console.log(found);
console.log(grade);
console.log("With this quote [``] you can concatenate variable in strings more easily using the '${}' syntax: My Name is: " + firstName + " " + lastName);
console.log(lastName);
console.log(anyType);
